name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Toutes les 10 minutes

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Renovate
        run: npx renovate
