name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1' # Tous les lundis à midi

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Renovate
        run: npx renovate
